var hierarchy =
[
    [ "MemoryHandler::BoundingBoxSlot", "structMemoryHandler_1_1BoundingBoxSlot.html", null ],
    [ "BoundsItem", "structBoundsItem.html", null ],
    [ "BuildSettings", "structBuildSettings.html", null ],
    [ "BVItem", "structBVItem.html", null ],
    [ "CachedModel", "structCachedModel.html", null ],
    [ "ConvexVolume", "structConvexVolume.html", null ],
    [ "CrowdToolParams", "structCrowdToolParams.html", null ],
    [ "CUSTOMVERTEX", "structCUSTOMVERTEX.html", null ],
    [ "DebugLine", "structDebugLine.html", null ],
    [ "DirtyEntry", "structDirtyEntry.html", null ],
    [ "dtBVNode", "structdtBVNode.html", null ],
    [ "dtCompressedTile", "structdtCompressedTile.html", null ],
    [ "dtCrowd", "classdtCrowd.html", null ],
    [ "dtCrowdAgent", "structdtCrowdAgent.html", null ],
    [ "dtCrowdAgentAnimation", "structdtCrowdAgentAnimation.html", null ],
    [ "dtCrowdAgentDebugInfo", "structdtCrowdAgentDebugInfo.html", null ],
    [ "dtCrowdAgentParams", "structdtCrowdAgentParams.html", null ],
    [ "dtCrowdNeighbour", "structdtCrowdNeighbour.html", null ],
    [ "dtFixedArray< T >", "classdtFixedArray.html", null ],
    [ "dtLayerMonotoneRegion", "structdtLayerMonotoneRegion.html", null ],
    [ "dtLayerSweepSpan", "structdtLayerSweepSpan.html", null ],
    [ "dtLink", "structdtLink.html", null ],
    [ "dtLocalBoundary", "classdtLocalBoundary.html", null ],
    [ "dtMeshHeader", "structdtMeshHeader.html", null ],
    [ "dtMeshTile", "structdtMeshTile.html", null ],
    [ "dtNavMesh", "classdtNavMesh.html", null ],
    [ "dtNavMeshCreateParams", "structdtNavMeshCreateParams.html", null ],
    [ "dtNavMeshParams", "structdtNavMeshParams.html", null ],
    [ "dtNavMeshQuery", "classdtNavMeshQuery.html", null ],
    [ "dtNode", "structdtNode.html", null ],
    [ "dtNodePool", "classdtNodePool.html", null ],
    [ "dtNodeQueue", "classdtNodeQueue.html", null ],
    [ "dtObstacleAvoidanceDebugData", "classdtObstacleAvoidanceDebugData.html", null ],
    [ "dtObstacleAvoidanceParams", "structdtObstacleAvoidanceParams.html", null ],
    [ "dtObstacleAvoidanceQuery", "classdtObstacleAvoidanceQuery.html", null ],
    [ "dtObstacleBox", "structdtObstacleBox.html", null ],
    [ "dtObstacleCircle", "structdtObstacleCircle.html", null ],
    [ "dtObstacleCylinder", "structdtObstacleCylinder.html", null ],
    [ "dtObstacleOrientedBox", "structdtObstacleOrientedBox.html", null ],
    [ "dtObstacleSegment", "structdtObstacleSegment.html", null ],
    [ "dtOffMeshConnection", "structdtOffMeshConnection.html", null ],
    [ "dtPathCorridor", "classdtPathCorridor.html", null ],
    [ "dtPathQueue", "classdtPathQueue.html", null ],
    [ "dtPoly", "structdtPoly.html", null ],
    [ "dtPolyDetail", "structdtPolyDetail.html", null ],
    [ "dtPolyQuery", "classdtPolyQuery.html", [
      [ "dtCollectPolysQuery", "classdtCollectPolysQuery.html", null ],
      [ "dtFindNearestPolyQuery", "classdtFindNearestPolyQuery.html", null ]
    ] ],
    [ "dtPolyState", "structdtPolyState.html", null ],
    [ "dtProximityGrid", "classdtProximityGrid.html", null ],
    [ "dtQueryFilter", "classdtQueryFilter.html", null ],
    [ "dtRaycastHit", "structdtRaycastHit.html", null ],
    [ "dtSegInterval", "structdtSegInterval.html", null ],
    [ "dtTempContour", "structdtTempContour.html", null ],
    [ "dtTileCache", "classdtTileCache.html", null ],
    [ "dtTileCacheAlloc", "structdtTileCacheAlloc.html", [
      [ "LinearAllocator", "structLinearAllocator.html", null ]
    ] ],
    [ "dtTileCacheCompressor", "structdtTileCacheCompressor.html", [
      [ "FastLZCompressor", "structFastLZCompressor.html", null ]
    ] ],
    [ "dtTileCacheContour", "structdtTileCacheContour.html", null ],
    [ "dtTileCacheContourSet", "structdtTileCacheContourSet.html", null ],
    [ "dtTileCacheLayer", "structdtTileCacheLayer.html", null ],
    [ "dtTileCacheLayerHeader", "structdtTileCacheLayerHeader.html", null ],
    [ "dtTileCacheMeshProcess", "structdtTileCacheMeshProcess.html", [
      [ "MeshProcess", "structMeshProcess.html", null ]
    ] ],
    [ "dtTileCacheObstacle", "structdtTileCacheObstacle.html", null ],
    [ "dtTileCacheParams", "structdtTileCacheParams.html", null ],
    [ "dtTileCachePolyMesh", "structdtTileCachePolyMesh.html", null ],
    [ "dtTileState", "structdtTileState.html", null ],
    [ "duDebugDraw", "structduDebugDraw.html", [
      [ "DebugDrawGL", "classDebugDrawGL.html", [
        [ "SampleDebugDraw", "classSampleDebugDraw.html", null ]
      ] ],
      [ "duDisplayList", "classduDisplayList.html", null ]
    ] ],
    [ "duFileIO", "structduFileIO.html", [
      [ "FileIO", "classFileIO.html", null ]
    ] ],
    [ "ExampleAppConsole", "structExampleAppConsole.html", null ],
    [ "ExampleAppDocuments", "structExampleAppDocuments.html", null ],
    [ "ExampleAppLog", "structExampleAppLog.html", null ],
    [ "ExampleAppPropertyEditor", "structExampleAppPropertyEditor.html", null ],
    [ "ExampleAsset", "structExampleAsset.html", null ],
    [ "ExampleAssetsBrowser", "structExampleAssetsBrowser.html", null ],
    [ "ExampleDualListBox", "structExampleDualListBox.html", null ],
    [ "ExampleMemberInfo", "structExampleMemberInfo.html", null ],
    [ "ExampleTreeNode", "structExampleTreeNode.html", null ],
    [ "ImGui::FileBrowser", "classImGui_1_1FileBrowser.html", null ],
    [ "FrameResources", "structFrameResources.html", null ],
    [ "MemoryHandler::GeometrySlot", "structMemoryHandler_1_1GeometrySlot.html", null ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", null ],
    [ "GLCheckerTexture", "classGLCheckerTexture.html", null ],
    [ "GraphParams", "structGraphParams.html", null ],
    [ "GtaHandler", "classGtaHandler.html", null ],
    [ "GtaHandlerMenu", "classGtaHandlerMenu.html", null ],
    [ "GtaNavGeometry", "classGtaNavGeometry.html", null ],
    [ "GtaNavProps", "classGtaNavProps.html", null ],
    [ "GtaNavTiles", "classGtaNavTiles.html", null ],
    [ "GuiState", "structGuiState.html", null ],
    [ "ImBitArray< BITCOUNT, OFFSET >", "structImBitArray.html", null ],
    [ "ImBitArray< ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN >", "structImBitArray.html", null ],
    [ "ImBitVector", "structImBitVector.html", null ],
    [ "ImChunkStream< T >", "structImChunkStream.html", null ],
    [ "ImChunkStream< ImGuiTableSettings >", "structImChunkStream.html", null ],
    [ "ImChunkStream< ImGuiWindowSettings >", "structImChunkStream.html", null ],
    [ "ImColor", "structImColor.html", null ],
    [ "ImDrawChannel", "structImDrawChannel.html", null ],
    [ "ImDrawCmd", "structImDrawCmd.html", null ],
    [ "ImDrawCmdHeader", "structImDrawCmdHeader.html", null ],
    [ "ImDrawData", "structImDrawData.html", null ],
    [ "ImDrawDataBuilder", "structImDrawDataBuilder.html", null ],
    [ "ImDrawList", "structImDrawList.html", null ],
    [ "ImDrawListSharedData", "structImDrawListSharedData.html", null ],
    [ "ImDrawListSplitter", "structImDrawListSplitter.html", null ],
    [ "ImDrawVert", "structImDrawVert.html", null ],
    [ "ImDrawVertAllegro", "structImDrawVertAllegro.html", null ],
    [ "ImFont", "structImFont.html", null ],
    [ "ImFontAtlas", "structImFontAtlas.html", null ],
    [ "ImFontAtlasBuilder", "structImFontAtlasBuilder.html", null ],
    [ "ImFontAtlasPostProcessData", "structImFontAtlasPostProcessData.html", null ],
    [ "ImFontAtlasRect", "structImFontAtlasRect.html", null ],
    [ "ImFontAtlasRectEntry", "structImFontAtlasRectEntry.html", null ],
    [ "ImFontBaked", "structImFontBaked.html", null ],
    [ "ImFontConfig", "structImFontConfig.html", null ],
    [ "ImFontGlyph", "structImFontGlyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "structImFontGlyphRangesBuilder.html", null ],
    [ "ImFontLoader", "structImFontLoader.html", null ],
    [ "ImFontStackData", "structImFontStackData.html", null ],
    [ "ImGL3WProcs", "unionImGL3WProcs.html", null ],
    [ "ImGui_ImplAllegro5_Data", "structImGui__ImplAllegro5__Data.html", null ],
    [ "ImGui_ImplDX10_Data", "structImGui__ImplDX10__Data.html", null ],
    [ "ImGui_ImplDX10_RenderState", "structImGui__ImplDX10__RenderState.html", null ],
    [ "ImGui_ImplDX10_Texture", "structImGui__ImplDX10__Texture.html", null ],
    [ "ImGui_ImplDX10_ViewportData", "structImGui__ImplDX10__ViewportData.html", null ],
    [ "ImGui_ImplDX11_Data", "structImGui__ImplDX11__Data.html", null ],
    [ "ImGui_ImplDX11_RenderState", "structImGui__ImplDX11__RenderState.html", null ],
    [ "ImGui_ImplDX11_Texture", "structImGui__ImplDX11__Texture.html", null ],
    [ "ImGui_ImplDX11_ViewportData", "structImGui__ImplDX11__ViewportData.html", null ],
    [ "ImGui_ImplDX12_Data", "structImGui__ImplDX12__Data.html", null ],
    [ "ImGui_ImplDX12_FrameContext", "structImGui__ImplDX12__FrameContext.html", null ],
    [ "ImGui_ImplDX12_InitInfo", "structImGui__ImplDX12__InitInfo.html", null ],
    [ "ImGui_ImplDX12_RenderBuffers", "structImGui__ImplDX12__RenderBuffers.html", null ],
    [ "ImGui_ImplDX12_RenderState", "structImGui__ImplDX12__RenderState.html", null ],
    [ "ImGui_ImplDX12_Texture", "structImGui__ImplDX12__Texture.html", null ],
    [ "ImGui_ImplDX12_ViewportData", "structImGui__ImplDX12__ViewportData.html", null ],
    [ "ImGui_ImplDX9_Data", "structImGui__ImplDX9__Data.html", null ],
    [ "ImGui_ImplDX9_ViewportData", "structImGui__ImplDX9__ViewportData.html", null ],
    [ "ImGui_ImplGlfw_Data", "structImGui__ImplGlfw__Data.html", null ],
    [ "ImGui_ImplGlfw_ViewportData", "structImGui__ImplGlfw__ViewportData.html", null ],
    [ "ImGui_ImplGlfw_WindowToContext", "structImGui__ImplGlfw__WindowToContext.html", null ],
    [ "ImGui_ImplOpenGL2_Data", "structImGui__ImplOpenGL2__Data.html", null ],
    [ "ImGui_ImplOpenGL3_Data", "structImGui__ImplOpenGL3__Data.html", null ],
    [ "ImGui_ImplSDL2_Data", "structImGui__ImplSDL2__Data.html", null ],
    [ "ImGui_ImplSDL2_ViewportData", "structImGui__ImplSDL2__ViewportData.html", null ],
    [ "ImGui_ImplSDL3_Data", "structImGui__ImplSDL3__Data.html", null ],
    [ "ImGui_ImplSDL3_ViewportData", "structImGui__ImplSDL3__ViewportData.html", null ],
    [ "ImGui_ImplSDLGPU3_Data", "structImGui__ImplSDLGPU3__Data.html", null ],
    [ "ImGui_ImplSDLGPU3_FrameData", "structImGui__ImplSDLGPU3__FrameData.html", null ],
    [ "ImGui_ImplSDLGPU3_InitInfo", "structImGui__ImplSDLGPU3__InitInfo.html", null ],
    [ "ImGui_ImplSDLGPU3_RenderState", "structImGui__ImplSDLGPU3__RenderState.html", null ],
    [ "ImGui_ImplSDLRenderer2_Data", "structImGui__ImplSDLRenderer2__Data.html", null ],
    [ "ImGui_ImplSDLRenderer2_RenderState", "structImGui__ImplSDLRenderer2__RenderState.html", null ],
    [ "ImGui_ImplSDLRenderer3_Data", "structImGui__ImplSDLRenderer3__Data.html", null ],
    [ "ImGui_ImplSDLRenderer3_RenderState", "structImGui__ImplSDLRenderer3__RenderState.html", null ],
    [ "ImGui_ImplStbTrueType_FontSrcData", "structImGui__ImplStbTrueType__FontSrcData.html", null ],
    [ "ImGui_ImplVulkan_Data", "structImGui__ImplVulkan__Data.html", null ],
    [ "ImGui_ImplVulkan_FrameRenderBuffers", "structImGui__ImplVulkan__FrameRenderBuffers.html", null ],
    [ "ImGui_ImplVulkan_InitInfo", "structImGui__ImplVulkan__InitInfo.html", null ],
    [ "ImGui_ImplVulkan_PipelineInfo", "structImGui__ImplVulkan__PipelineInfo.html", null ],
    [ "ImGui_ImplVulkan_RenderState", "structImGui__ImplVulkan__RenderState.html", null ],
    [ "ImGui_ImplVulkan_Texture", "structImGui__ImplVulkan__Texture.html", null ],
    [ "ImGui_ImplVulkan_ViewportData", "structImGui__ImplVulkan__ViewportData.html", null ],
    [ "ImGui_ImplVulkan_WindowRenderBuffers", "structImGui__ImplVulkan__WindowRenderBuffers.html", null ],
    [ "ImGui_ImplVulkanH_Frame", "structImGui__ImplVulkanH__Frame.html", null ],
    [ "ImGui_ImplVulkanH_FrameSemaphores", "structImGui__ImplVulkanH__FrameSemaphores.html", null ],
    [ "ImGui_ImplVulkanH_Window", "structImGui__ImplVulkanH__Window.html", null ],
    [ "ImGui_ImplWGPU_CreateSurfaceInfo", "structImGui__ImplWGPU__CreateSurfaceInfo.html", null ],
    [ "ImGui_ImplWGPU_Data", "structImGui__ImplWGPU__Data.html", null ],
    [ "ImGui_ImplWGPU_InitInfo", "structImGui__ImplWGPU__InitInfo.html", null ],
    [ "ImGui_ImplWGPU_RenderState", "structImGui__ImplWGPU__RenderState.html", null ],
    [ "ImGui_ImplWGPU_Texture", "structImGui__ImplWGPU__Texture.html", null ],
    [ "ImGui_ImplWin32_Data", "structImGui__ImplWin32__Data.html", null ],
    [ "ImGui_ImplWin32_ViewportData", "structImGui__ImplWin32__ViewportData.html", null ],
    [ "ImGuiBoxSelectState", "structImGuiBoxSelectState.html", null ],
    [ "ImGuiColorMod", "structImGuiColorMod.html", null ],
    [ "ImGuiComboPreviewData", "structImGuiComboPreviewData.html", null ],
    [ "ImGuiContext", "structImGuiContext.html", null ],
    [ "ImGuiContextHook", "structImGuiContextHook.html", null ],
    [ "ImGuiDataTypeInfo", "structImGuiDataTypeInfo.html", null ],
    [ "ImGuiDataTypeStorage", "structImGuiDataTypeStorage.html", null ],
    [ "ImGuiDeactivatedItemData", "structImGuiDeactivatedItemData.html", null ],
    [ "ImGuiDebugAllocEntry", "structImGuiDebugAllocEntry.html", null ],
    [ "ImGuiDebugAllocInfo", "structImGuiDebugAllocInfo.html", null ],
    [ "ImGuiDebugItemPathQuery", "structImGuiDebugItemPathQuery.html", null ],
    [ "ImGuiDemoWindowData", "structImGuiDemoWindowData.html", null ],
    [ "ImGuiDockContext", "structImGuiDockContext.html", null ],
    [ "ImGuiDockContextPruneNodeData", "structImGuiDockContextPruneNodeData.html", null ],
    [ "ImGuiDockNode", "structImGuiDockNode.html", null ],
    [ "ImGuiDockNodeSettings", "structImGuiDockNodeSettings.html", null ],
    [ "ImGuiDockNodeTreeInfo", "structImGuiDockNodeTreeInfo.html", null ],
    [ "ImGuiDockPreviewData", "structImGuiDockPreviewData.html", null ],
    [ "ImGuiDockRequest", "structImGuiDockRequest.html", null ],
    [ "ImGuiErrorRecoveryState", "structImGuiErrorRecoveryState.html", null ],
    [ "ImGuiFocusScopeData", "structImGuiFocusScopeData.html", null ],
    [ "ImGuiGetNameFromIndexOldToNewCallbackData", "structImGuiGetNameFromIndexOldToNewCallbackData.html", null ],
    [ "imguiGfxCmd", "structimguiGfxCmd.html", null ],
    [ "imguiGfxLine", "structimguiGfxLine.html", null ],
    [ "imguiGfxRect", "structimguiGfxRect.html", null ],
    [ "imguiGfxText", "structimguiGfxText.html", null ],
    [ "ImGuiGroupData", "structImGuiGroupData.html", null ],
    [ "ImGuiIDStackTool", "structImGuiIDStackTool.html", null ],
    [ "ImGuiInputEvent", "structImGuiInputEvent.html", null ],
    [ "ImGuiInputEventAppFocused", "structImGuiInputEventAppFocused.html", null ],
    [ "ImGuiInputEventKey", "structImGuiInputEventKey.html", null ],
    [ "ImGuiInputEventMouseButton", "structImGuiInputEventMouseButton.html", null ],
    [ "ImGuiInputEventMousePos", "structImGuiInputEventMousePos.html", null ],
    [ "ImGuiInputEventMouseViewport", "structImGuiInputEventMouseViewport.html", null ],
    [ "ImGuiInputEventMouseWheel", "structImGuiInputEventMouseWheel.html", null ],
    [ "ImGuiInputEventText", "structImGuiInputEventText.html", null ],
    [ "ImGuiInputTextCallbackData", "structImGuiInputTextCallbackData.html", null ],
    [ "ImGuiInputTextDeactivatedState", "structImGuiInputTextDeactivatedState.html", null ],
    [ "ImGuiInputTextState", "structImGuiInputTextState.html", null ],
    [ "ImGuiIO", "structImGuiIO.html", null ],
    [ "ImGuiKeyData", "structImGuiKeyData.html", null ],
    [ "ImGuiKeyOwnerData", "structImGuiKeyOwnerData.html", null ],
    [ "ImGuiKeyRoutingData", "structImGuiKeyRoutingData.html", null ],
    [ "ImGuiKeyRoutingTable", "structImGuiKeyRoutingTable.html", null ],
    [ "ImGuiLastItemData", "structImGuiLastItemData.html", null ],
    [ "ImGuiListClipper", "structImGuiListClipper.html", null ],
    [ "ImGuiListClipperData", "structImGuiListClipperData.html", null ],
    [ "ImGuiListClipperRange", "structImGuiListClipperRange.html", null ],
    [ "ImGuiLocEntry", "structImGuiLocEntry.html", null ],
    [ "ImGuiMenuColumns", "structImGuiMenuColumns.html", null ],
    [ "ImGuiMetricsConfig", "structImGuiMetricsConfig.html", null ],
    [ "ImGuiMultiSelectIO", "structImGuiMultiSelectIO.html", null ],
    [ "ImGuiMultiSelectState", "structImGuiMultiSelectState.html", null ],
    [ "ImGuiMultiSelectTempData", "structImGuiMultiSelectTempData.html", null ],
    [ "ImGuiNavItemData", "structImGuiNavItemData.html", null ],
    [ "ImGuiNextItemData", "structImGuiNextItemData.html", null ],
    [ "ImGuiNextWindowData", "structImGuiNextWindowData.html", null ],
    [ "ImGuiOldColumnData", "structImGuiOldColumnData.html", null ],
    [ "ImGuiOldColumns", "structImGuiOldColumns.html", null ],
    [ "ImGuiOnceUponAFrame", "structImGuiOnceUponAFrame.html", null ],
    [ "ImGuiPayload", "structImGuiPayload.html", null ],
    [ "ImGuiPlatformImeData", "structImGuiPlatformImeData.html", null ],
    [ "ImGuiPlatformIO", "structImGuiPlatformIO.html", null ],
    [ "ImGuiPlatformMonitor", "structImGuiPlatformMonitor.html", null ],
    [ "ImGuiPlotArrayGetterData", "structImGuiPlotArrayGetterData.html", null ],
    [ "ImGuiPopupData", "structImGuiPopupData.html", null ],
    [ "ImGuiPtrOrIndex", "structImGuiPtrOrIndex.html", null ],
    [ "ImGuiResizeBorderDef", "structImGuiResizeBorderDef.html", null ],
    [ "ImGuiResizeGripDef", "structImGuiResizeGripDef.html", null ],
    [ "ImGuiSelectionBasicStorage", "structImGuiSelectionBasicStorage.html", [
      [ "ExampleSelectionWithDeletion", "structExampleSelectionWithDeletion.html", null ]
    ] ],
    [ "ImGuiSelectionExternalStorage", "structImGuiSelectionExternalStorage.html", null ],
    [ "ImGuiSelectionRequest", "structImGuiSelectionRequest.html", null ],
    [ "ImGuiSettingsHandler", "structImGuiSettingsHandler.html", null ],
    [ "ImGuiShrinkWidthItem", "structImGuiShrinkWidthItem.html", null ],
    [ "ImGuiSizeCallbackData", "structImGuiSizeCallbackData.html", null ],
    [ "ImGuiStackLevelInfo", "structImGuiStackLevelInfo.html", null ],
    [ "ImGuiStorage", "structImGuiStorage.html", null ],
    [ "ImGuiStoragePair", "structImGuiStoragePair.html", null ],
    [ "ImGuiStyle", "structImGuiStyle.html", null ],
    [ "ImGuiStyleMod", "structImGuiStyleMod.html", null ],
    [ "ImGuiStyleVarInfo", "structImGuiStyleVarInfo.html", null ],
    [ "ImGuiTabBar", "structImGuiTabBar.html", null ],
    [ "ImGuiTabBarSection", "structImGuiTabBarSection.html", null ],
    [ "ImGuiTabItem", "structImGuiTabItem.html", null ],
    [ "ImGuiTable", "structImGuiTable.html", null ],
    [ "ImGuiTableCellData", "structImGuiTableCellData.html", null ],
    [ "ImGuiTableColumn", "structImGuiTableColumn.html", null ],
    [ "ImGuiTableColumnSettings", "structImGuiTableColumnSettings.html", null ],
    [ "ImGuiTableColumnSortSpecs", "structImGuiTableColumnSortSpecs.html", null ],
    [ "ImGuiTableHeaderData", "structImGuiTableHeaderData.html", null ],
    [ "ImGuiTableInstanceData", "structImGuiTableInstanceData.html", null ],
    [ "ImGuiTableSettings", "structImGuiTableSettings.html", null ],
    [ "ImGuiTableSortSpecs", "structImGuiTableSortSpecs.html", null ],
    [ "ImGuiTableTempData", "structImGuiTableTempData.html", null ],
    [ "ImGuiTextBuffer", "structImGuiTextBuffer.html", null ],
    [ "ImGuiTextFilter", "structImGuiTextFilter.html", null ],
    [ "ImGuiTextIndex", "structImGuiTextIndex.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "structImGuiTextFilter_1_1ImGuiTextRange.html", null ],
    [ "ImGuiTreeNodeStackData", "structImGuiTreeNodeStackData.html", null ],
    [ "ImGuiTypingSelectRequest", "structImGuiTypingSelectRequest.html", null ],
    [ "ImGuiTypingSelectState", "structImGuiTypingSelectState.html", null ],
    [ "ImGuiViewport", "structImGuiViewport.html", [
      [ "ImGuiViewportP", "structImGuiViewportP.html", null ]
    ] ],
    [ "ImGuiWindow", "structImGuiWindow.html", null ],
    [ "ImGuiWindowClass", "structImGuiWindowClass.html", null ],
    [ "ImGuiWindowDockStyle", "structImGuiWindowDockStyle.html", null ],
    [ "ImGuiWindowSettings", "structImGuiWindowSettings.html", null ],
    [ "ImGuiWindowStackData", "structImGuiWindowStackData.html", null ],
    [ "ImGuiWindowTempData", "structImGuiWindowTempData.html", null ],
    [ "ImNewWrapper", "structImNewWrapper.html", null ],
    [ "ImPool< T >", "structImPool.html", null ],
    [ "ImPool< ImGuiMultiSelectState >", "structImPool.html", null ],
    [ "ImPool< ImGuiTabBar >", "structImPool.html", null ],
    [ "ImPool< ImGuiTable >", "structImPool.html", null ],
    [ "ImRect", "structImRect.html", null ],
    [ "ImSpan< T >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableCellData >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableColumn >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableColumnIdx >", "structImSpan.html", null ],
    [ "ImSpanAllocator< CHUNKS >", "structImSpanAllocator.html", null ],
    [ "ImStableVector< T, BLOCK_SIZE >", "structImStableVector.html", null ],
    [ "ImStableVector< ImFontBaked, 32 >", "structImStableVector.html", null ],
    [ "ImTextureData", "structImTextureData.html", null ],
    [ "ImTextureRect", "structImTextureRect.html", null ],
    [ "ImTextureRef", "structImTextureRef.html", null ],
    [ "ImTriangulator", "structImTriangulator.html", null ],
    [ "ImTriangulatorNode", "structImTriangulatorNode.html", null ],
    [ "ImTriangulatorNodeSpan", "structImTriangulatorNodeSpan.html", null ],
    [ "ImVec1", "structImVec1.html", null ],
    [ "ImVec2", "structImVec2.html", null ],
    [ "ImVec2i", "structImVec2i.html", null ],
    [ "ImVec2ih", "structImVec2ih.html", null ],
    [ "ImVec4", "structImVec4.html", null ],
    [ "ImVector< T >", "structImVector.html", null ],
    [ "ImVector< char * >", "structImVector.html", null ],
    [ "ImVector< char >", "structImVector.html", null ],
    [ "ImVector< const char * >", "structImVector.html", null ],
    [ "ImVector< DXGI_SWAP_CHAIN_DESC >", "structImVector.html", null ],
    [ "ImVector< ExampleAsset >", "structImVector.html", null ],
    [ "ImVector< ExampleTreeNode * >", "structImVector.html", null ],
    [ "ImVector< float >", "structImVector.html", null ],
    [ "ImVector< ImDrawChannel >", "structImVector.html", null ],
    [ "ImVector< ImDrawCmd >", "structImVector.html", null ],
    [ "ImVector< ImDrawIdx >", "structImVector.html", null ],
    [ "ImVector< ImDrawList * >", "structImVector.html", null ],
    [ "ImVector< ImDrawListSharedData * >", "structImVector.html", null ],
    [ "ImVector< ImDrawVert >", "structImVector.html", null ],
    [ "ImVector< ImDrawVertAllegro >", "structImVector.html", null ],
    [ "ImVector< ImFont * >", "structImVector.html", null ],
    [ "ImVector< ImFontAtlas * >", "structImVector.html", null ],
    [ "ImVector< ImFontAtlasRectEntry >", "structImVector.html", null ],
    [ "ImVector< ImFontBaked * >", "structImVector.html", null ],
    [ "ImVector< ImFontConfig * >", "structImVector.html", null ],
    [ "ImVector< ImFontConfig >", "structImVector.html", null ],
    [ "ImVector< ImFontGlyph >", "structImVector.html", null ],
    [ "ImVector< ImFontStackData >", "structImVector.html", null ],
    [ "ImVector< ImGui_ImplVulkan_FrameRenderBuffers >", "structImVector.html", null ],
    [ "ImVector< ImGui_ImplVulkanH_Frame >", "structImVector.html", null ],
    [ "ImVector< ImGui_ImplVulkanH_FrameSemaphores >", "structImVector.html", null ],
    [ "ImVector< ImGuiColorMod >", "structImVector.html", null ],
    [ "ImVector< ImGuiContextHook >", "structImVector.html", null ],
    [ "ImVector< ImGuiDockNodeSettings >", "structImVector.html", null ],
    [ "ImVector< ImGuiDockRequest >", "structImVector.html", null ],
    [ "ImVector< ImGuiFocusScopeData >", "structImVector.html", null ],
    [ "ImVector< ImGuiGroupData >", "structImVector.html", null ],
    [ "ImVector< ImGuiID >", "structImVector.html", null ],
    [ "ImVector< ImGuiInputEvent >", "structImVector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "structImVector.html", null ],
    [ "ImVector< ImGuiKeyRoutingData >", "structImVector.html", null ],
    [ "ImVector< ImGuiListClipperData >", "structImVector.html", null ],
    [ "ImVector< ImGuiListClipperRange >", "structImVector.html", null ],
    [ "ImVector< ImGuiMultiSelectState >", "structImVector.html", null ],
    [ "ImVector< ImGuiMultiSelectTempData >", "structImVector.html", null ],
    [ "ImVector< ImGuiOldColumnData >", "structImVector.html", null ],
    [ "ImVector< ImGuiOldColumns >", "structImVector.html", null ],
    [ "ImVector< ImGuiPlatformMonitor >", "structImVector.html", null ],
    [ "ImVector< ImGuiPopupData >", "structImVector.html", null ],
    [ "ImVector< ImGuiPtrOrIndex >", "structImVector.html", null ],
    [ "ImVector< ImGuiSelectionRequest >", "structImVector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "structImVector.html", null ],
    [ "ImVector< ImGuiShrinkWidthItem >", "structImVector.html", null ],
    [ "ImVector< ImGuiStackLevelInfo >", "structImVector.html", null ],
    [ "ImVector< ImGuiStoragePair >", "structImVector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "structImVector.html", null ],
    [ "ImVector< ImGuiTabBar >", "structImVector.html", null ],
    [ "ImVector< ImGuiTabItem >", "structImVector.html", null ],
    [ "ImVector< ImGuiTable >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableColumnSortSpecs >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableHeaderData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableInstanceData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableTempData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTextFilter::ImGuiTextRange >", "structImVector.html", null ],
    [ "ImVector< ImGuiTreeNodeStackData >", "structImVector.html", null ],
    [ "ImVector< ImGuiViewport * >", "structImVector.html", null ],
    [ "ImVector< ImGuiViewportP * >", "structImVector.html", null ],
    [ "ImVector< ImGuiWindow * >", "structImVector.html", null ],
    [ "ImVector< ImGuiWindowStackData >", "structImVector.html", null ],
    [ "ImVector< ImTextureData * >", "structImVector.html", null ],
    [ "ImVector< ImTextureRect >", "structImVector.html", null ],
    [ "ImVector< ImTextureRef >", "structImVector.html", null ],
    [ "ImVector< ImU16 >", "structImVector.html", null ],
    [ "ImVector< ImU32 >", "structImVector.html", null ],
    [ "ImVector< ImU8 >", "structImVector.html", null ],
    [ "ImVector< ImVec2 >", "structImVector.html", null ],
    [ "ImVector< ImVec4 >", "structImVector.html", null ],
    [ "ImVector< ImWchar >", "structImVector.html", null ],
    [ "ImVector< int >", "structImVector.html", null ],
    [ "ImVector< MyDocument * >", "structImVector.html", null ],
    [ "ImVector< MyDocument >", "structImVector.html", null ],
    [ "ImVector< SDL_FColor >", "structImVector.html", null ],
    [ "ImVector< SDL_GameController * >", "structImVector.html", null ],
    [ "ImVector< SDL_Gamepad * >", "structImVector.html", null ],
    [ "ImVector< stbrp_node >", "structImVector.html", null ],
    [ "ImVector< T * >", "structImVector.html", null ],
    [ "ImVector< unsigned char >", "structImVector.html", null ],
    [ "ImVector< VkFormat >", "structImVector.html", null ],
    [ "InputGeom", "classInputGeom.html", null ],
    [ "MemoryHandler", "classMemoryHandler.html", null ],
    [ "Mesh", "classMesh.html", null ],
    [ "MyDocument", "structMyDocument.html", null ],
    [ "NavmeshBuildInput", "structNavmeshBuildInput.html", null ],
    [ "NavMeshContext", "structNavMeshContext.html", null ],
    [ "NavMeshData", "classNavMeshData.html", null ],
    [ "NavMeshDefinition", "structNavMeshDefinition.html", null ],
    [ "NavmeshFlags", "classNavmeshFlags.html", null ],
    [ "NavmeshGenerationSettings", "structNavmeshGenerationSettings.html", null ],
    [ "NavMeshSetHeader", "structNavMeshSetHeader.html", null ],
    [ "NavMeshTileBuildContext", "structNavMeshTileBuildContext.html", null ],
    [ "NavMeshTileHeader", "structNavMeshTileHeader.html", null ],
    [ "ObjLoader", "classObjLoader.html", null ],
    [ "OffmeshLink", "structOffmeshLink.html", null ],
    [ "MemoryHandler::OffmeshLinkSlot", "structMemoryHandler_1_1OffmeshLinkSlot.html", null ],
    [ "PropInstance", "structPropInstance.html", null ],
    [ "RasterizationContext", "structRasterizationContext.html", null ],
    [ "Ray", "structRay.html", null ],
    [ "rcChunkyTriMesh", "structrcChunkyTriMesh.html", null ],
    [ "rcChunkyTriMeshNode", "structrcChunkyTriMeshNode.html", null ],
    [ "rcCompactCell", "structrcCompactCell.html", null ],
    [ "rcCompactHeightfield", "structrcCompactHeightfield.html", null ],
    [ "rcCompactSpan", "structrcCompactSpan.html", null ],
    [ "rcConfig", "structrcConfig.html", null ],
    [ "rcContext", "classrcContext.html", [
      [ "BuildContext", "classBuildContext.html", null ]
    ] ],
    [ "rcContour", "structrcContour.html", null ],
    [ "rcContourHole", "structrcContourHole.html", null ],
    [ "rcContourRegion", "structrcContourRegion.html", null ],
    [ "rcContourSet", "structrcContourSet.html", null ],
    [ "rcEdge", "structrcEdge.html", null ],
    [ "rcHeightfield", "structrcHeightfield.html", null ],
    [ "rcHeightfieldLayer", "structrcHeightfieldLayer.html", null ],
    [ "rcHeightfieldLayerSet", "structrcHeightfieldLayerSet.html", null ],
    [ "rcHeightPatch", "structrcHeightPatch.html", null ],
    [ "rcLayerRegion", "structrcLayerRegion.html", null ],
    [ "rcLayerSweepSpan", "structrcLayerSweepSpan.html", null ],
    [ "rcMeshLoaderObj", "classrcMeshLoaderObj.html", null ],
    [ "rcNewTag", "structrcNewTag.html", null ],
    [ "rcPolyMesh", "structrcPolyMesh.html", null ],
    [ "rcPolyMeshDetail", "structrcPolyMeshDetail.html", null ],
    [ "rcPotentialDiagonal", "structrcPotentialDiagonal.html", null ],
    [ "rcRegion", "structrcRegion.html", null ],
    [ "rcScopedDelete< T >", "classrcScopedDelete.html", null ],
    [ "rcScopedTimer", "classrcScopedTimer.html", null ],
    [ "rcSpan", "structrcSpan.html", null ],
    [ "rcSpanPool", "structrcSpanPool.html", null ],
    [ "rcSweepSpan", "structrcSweepSpan.html", null ],
    [ "rcVectorBase< T, H >", "classrcVectorBase.html", [
      [ "rcTempVector< int >", "classrcTempVector.html", null ]
    ] ],
    [ "rcVectorBase< int, RC_ALLOC_TEMP >", "classrcVectorBase.html", null ],
    [ "rcVectorBase< T, RC_ALLOC_PERM >", "classrcVectorBase.html", [
      [ "rcPermVector< T >", "classrcPermVector.html", null ]
    ] ],
    [ "rcVectorBase< T, RC_ALLOC_TEMP >", "classrcVectorBase.html", [
      [ "rcTempVector< T >", "classrcTempVector.html", null ]
    ] ],
    [ "RendererGL", "classRendererGL.html", null ],
    [ "RenderResources", "structRenderResources.html", null ],
    [ "MemoryHandler::RouteRequestSlot", "structMemoryHandler_1_1RouteRequestSlot.html", null ],
    [ "MemoryHandler::RouteResultPoint", "structMemoryHandler_1_1RouteResultPoint.html", null ],
    [ "Sample", "classSample.html", [
      [ "Sample_Debug", "classSample__Debug.html", null ],
      [ "Sample_SoloMesh", "classSample__SoloMesh.html", null ],
      [ "Sample_TempObstacles", "classSample__TempObstacles.html", null ],
      [ "Sample_TileMesh", "classSample__TileMesh.html", null ]
    ] ],
    [ "SampleItem", "structSampleItem.html", null ],
    [ "SampleTool", "structSampleTool.html", [
      [ "ConvexVolumeTool", "classConvexVolumeTool.html", null ],
      [ "CrowdTool", "classCrowdTool.html", null ],
      [ "NavMeshPruneTool", "classNavMeshPruneTool.html", null ],
      [ "NavMeshTesterTool", "classNavMeshTesterTool.html", null ],
      [ "NavMeshTileTool", "classNavMeshTileTool.html", null ],
      [ "OffMeshConnectionTool", "classOffMeshConnectionTool.html", null ],
      [ "TempObstacleCreateTool", "classTempObstacleCreateTool.html", null ],
      [ "TempObstacleHilightTool", "classTempObstacleHilightTool.html", null ]
    ] ],
    [ "SampleToolState", "structSampleToolState.html", [
      [ "CrowdToolState", "classCrowdToolState.html", null ]
    ] ],
    [ "SDL_AssertData", "structSDL__AssertData.html", null ],
    [ "SDL_atomic_t", "structSDL__atomic__t.html", null ],
    [ "SDL_AudioCVT", "structSDL__AudioCVT.html", null ],
    [ "SDL_AudioDeviceEvent", "structSDL__AudioDeviceEvent.html", null ],
    [ "SDL_AudioSpec", "structSDL__AudioSpec.html", null ],
    [ "SDL_Color", "structSDL__Color.html", null ],
    [ "SDL_CommonEvent", "structSDL__CommonEvent.html", null ],
    [ "SDL_ControllerAxisEvent", "structSDL__ControllerAxisEvent.html", null ],
    [ "SDL_ControllerButtonEvent", "structSDL__ControllerButtonEvent.html", null ],
    [ "SDL_ControllerDeviceEvent", "structSDL__ControllerDeviceEvent.html", null ],
    [ "SDL_ControllerSensorEvent", "structSDL__ControllerSensorEvent.html", null ],
    [ "SDL_ControllerTouchpadEvent", "structSDL__ControllerTouchpadEvent.html", null ],
    [ "SDL_DisplayEvent", "structSDL__DisplayEvent.html", null ],
    [ "SDL_DisplayMode", "structSDL__DisplayMode.html", null ],
    [ "SDL_DollarGestureEvent", "structSDL__DollarGestureEvent.html", null ],
    [ "SDL_DropEvent", "structSDL__DropEvent.html", null ],
    [ "SDL_Event", "unionSDL__Event.html", null ],
    [ "SDL_Finger", "structSDL__Finger.html", null ],
    [ "SDL_FPoint", "structSDL__FPoint.html", null ],
    [ "SDL_FRect", "structSDL__FRect.html", null ],
    [ "SDL_GameControllerButtonBind", "structSDL__GameControllerButtonBind.html", null ],
    [ "SDL_GUID", "structSDL__GUID.html", null ],
    [ "SDL_HapticCondition", "structSDL__HapticCondition.html", null ],
    [ "SDL_HapticConstant", "structSDL__HapticConstant.html", null ],
    [ "SDL_HapticCustom", "structSDL__HapticCustom.html", null ],
    [ "SDL_HapticDirection", "structSDL__HapticDirection.html", null ],
    [ "SDL_HapticEffect", "unionSDL__HapticEffect.html", null ],
    [ "SDL_HapticLeftRight", "structSDL__HapticLeftRight.html", null ],
    [ "SDL_HapticPeriodic", "structSDL__HapticPeriodic.html", null ],
    [ "SDL_HapticRamp", "structSDL__HapticRamp.html", null ],
    [ "SDL_hid_device_info", "structSDL__hid__device__info.html", null ],
    [ "SDL_JoyAxisEvent", "structSDL__JoyAxisEvent.html", null ],
    [ "SDL_JoyBallEvent", "structSDL__JoyBallEvent.html", null ],
    [ "SDL_JoyBatteryEvent", "structSDL__JoyBatteryEvent.html", null ],
    [ "SDL_JoyButtonEvent", "structSDL__JoyButtonEvent.html", null ],
    [ "SDL_JoyDeviceEvent", "structSDL__JoyDeviceEvent.html", null ],
    [ "SDL_JoyHatEvent", "structSDL__JoyHatEvent.html", null ],
    [ "SDL_KeyboardEvent", "structSDL__KeyboardEvent.html", null ],
    [ "SDL_Keysym", "structSDL__Keysym.html", null ],
    [ "SDL_Locale", "structSDL__Locale.html", null ],
    [ "SDL_MessageBoxButtonData", "structSDL__MessageBoxButtonData.html", null ],
    [ "SDL_MessageBoxColor", "structSDL__MessageBoxColor.html", null ],
    [ "SDL_MessageBoxColorScheme", "structSDL__MessageBoxColorScheme.html", null ],
    [ "SDL_MessageBoxData", "structSDL__MessageBoxData.html", null ],
    [ "SDL_MouseButtonEvent", "structSDL__MouseButtonEvent.html", null ],
    [ "SDL_MouseMotionEvent", "structSDL__MouseMotionEvent.html", null ],
    [ "SDL_MouseWheelEvent", "structSDL__MouseWheelEvent.html", null ],
    [ "SDL_MultiGestureEvent", "structSDL__MultiGestureEvent.html", null ],
    [ "SDL_Palette", "structSDL__Palette.html", null ],
    [ "SDL_PixelFormat", "structSDL__PixelFormat.html", null ],
    [ "SDL_Point", "structSDL__Point.html", null ],
    [ "SDL_QuitEvent", "structSDL__QuitEvent.html", null ],
    [ "SDL_Rect", "structSDL__Rect.html", null ],
    [ "SDL_RendererInfo", "structSDL__RendererInfo.html", null ],
    [ "SDL_RWops", "structSDL__RWops.html", null ],
    [ "SDL_SensorEvent", "structSDL__SensorEvent.html", null ],
    [ "SDL_Surface", "structSDL__Surface.html", null ],
    [ "SDL_SysWMEvent", "structSDL__SysWMEvent.html", null ],
    [ "SDL_SysWMinfo", "structSDL__SysWMinfo.html", null ],
    [ "SDL_SysWMmsg", "structSDL__SysWMmsg.html", null ],
    [ "SDL_TextEditingEvent", "structSDL__TextEditingEvent.html", null ],
    [ "SDL_TextEditingExtEvent", "structSDL__TextEditingExtEvent.html", null ],
    [ "SDL_TextInputEvent", "structSDL__TextInputEvent.html", null ],
    [ "SDL_TouchFingerEvent", "structSDL__TouchFingerEvent.html", null ],
    [ "SDL_UserEvent", "structSDL__UserEvent.html", null ],
    [ "SDL_version", "structSDL__version.html", null ],
    [ "SDL_Vertex", "structSDL__Vertex.html", null ],
    [ "SDL_VirtualJoystickDesc", "structSDL__VirtualJoystickDesc.html", null ],
    [ "SDL_WindowEvent", "structSDL__WindowEvent.html", null ],
    [ "SDL_WindowShapeMode", "structSDL__WindowShapeMode.html", null ],
    [ "SDL_WindowShapeParams", "unionSDL__WindowShapeParams.html", null ],
    [ "SDLTest_CommonState", "structSDLTest__CommonState.html", null ],
    [ "SDLTest_Crc32Context", "structSDLTest__Crc32Context.html", null ],
    [ "SDLTest_Md5Context", "structSDLTest__Md5Context.html", null ],
    [ "SDLTest_RandomContext", "structSDLTest__RandomContext.html", null ],
    [ "SDLTest_SurfaceImage_s", "structSDLTest__SurfaceImage__s.html", null ],
    [ "SDLTest_TestCaseReference", "structSDLTest__TestCaseReference.html", null ],
    [ "SDLTest_TestSuiteReference", "structSDLTest__TestSuiteReference.html", null ],
    [ "SDLTest_TextWindow", "structSDLTest__TextWindow.html", null ],
    [ "STB_TexteditState", "structSTB__TexteditState.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_context_opaque", "structstbrp__context__opaque.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "StbTexteditRow", "structStbTexteditRow.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_kerningentry", "structstbtt__kerningentry.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "structStbUndoRecord.html", null ],
    [ "StbUndoState", "structStbUndoState.html", null ],
    [ "TempVertex", "structTempVertex.html", null ],
    [ "TestCase", "classTestCase.html", null ],
    [ "TileCacheData", "structTileCacheData.html", null ],
    [ "TileCacheSetHeader", "structTileCacheSetHeader.html", null ],
    [ "TileCacheTileHeader", "structTileCacheTileHeader.html", null ],
    [ "Uniforms", "structUniforms.html", null ],
    [ "ValueHistory", "classValueHistory.html", null ],
    [ "MemoryHandler::Vector3", "structMemoryHandler_1_1Vector3.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX10", "structVERTEX__CONSTANT__BUFFER__DX10.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX11", "structVERTEX__CONSTANT__BUFFER__DX11.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX12", "structVERTEX__CONSTANT__BUFFER__DX12.html", null ],
    [ "ViewerApp", "classViewerApp.html", null ],
    [ "ViewerCamera", "classViewerCamera.html", null ]
];